import { DirectionalLight, Vector3 } from "@babylonjs/core";
import { GetAsyncSceneIdentifier } from "@engine/AsyncAssets";
import {
    LightRebuildTag,
    DirectionalLight as DLightComp,
} from "@engine/Autogenerated/babylonburst_ServerTypings_autogenerated";
import { EntVector3 } from "@engine/EntitySystem/CoreComponents";
import { EntitySpecification } from "@engine/EntitySystem/EntityMsgpackConverter";
import { GameEcosystem } from "@engine/GameEcosystem";

var generatedDirectionLights: { [sceneId: string]: { [ent: string]: DirectionalLight } } = {};

export function RunLightsSystem(ecosystem: GameEcosystem) {
    const rebuildLights = ecosystem.wasmWrapper.GetEntitiesWithData([LightRebuildTag], [], false);
    const rebuildEnts = Object.keys(rebuildLights);
    for (var r = 0; r < rebuildEnts.length; r++) {
        const rebuildEnt = parseInt(rebuildEnts[r]);
        const rebuildEntData = rebuildLights[rebuildEnt];
        GenerateDirectionalLight(rebuildEntData, rebuildEnt);
    }

    function GenerateDirectionalLight(rebuildEntData: EntitySpecification, rebuildEnt: number) {
        if (rebuildEntData[DLightComp.name]) {
            if (!generatedDirectionLights[GetAsyncSceneIdentifier(ecosystem.scene)]) {
                generatedDirectionLights[GetAsyncSceneIdentifier(ecosystem.scene)] = {};
            }
            const dirLights = generatedDirectionLights[GetAsyncSceneIdentifier(ecosystem.scene)];
            const directData = rebuildEntData[DLightComp.name] as DLightComp;
            if (!dirLights[rebuildEnt]) {
                dirLights[rebuildEnt] = new DirectionalLight(
                    "Ent" + rebuildEnt + "_DirectLight",
                    EntVector3.GetVector3(directData.Direction),
                    ecosystem.scene
                );
            }
            //TODO: Set other info
            const light = dirLights[rebuildEnt] as DirectionalLight;
            light.position = EntVector3.GetVector3(directData.Position);
            light.direction = EntVector3.GetVector3(directData.Direction);
            ecosystem.wasmWrapper.DelayedRemoveComponent(rebuildEnt, LightRebuildTag.name);
            console.log(light);
        }
    }
}
