#pragma once
#include "Engine/Entities/EntityMacros.hpp"
#include "Engine/Utils/MsgpackHelpers.h"
#include "Engine/Utils/StringUtils.h"
#include "msgpack.hpp"
#include <iostream>
#include <string>

//Specifies a saved Editor material to use
struct MaterialSpecifier {
    //The path to get to our zipped material archive on S3 (eg Folder/Material~8~)
    CPROPERTY(std::string, FilePath, NO_DEFAULT);
    //The name of the file that contains our Material
    CPROPERTY(std::string, FileName, NO_DEFAULT);

    bool operator==(const MaterialSpecifier& rhs) const {
        if (FilePath != rhs.FilePath) {
            return false;
        }
        return true;
    }

    bool operator!=(const MaterialSpecifier& other) const {
        return !(*this == other);
    }

    MSGPACK_PACK_FUNC(FilePath, FileName)

    MSGPACK_UNPACK_FUNC(FilePath, FileName)
};

//---- AUTOGENERATED ---
#include "Engine/Rendering/MaterialSpecifier_autogenerated.h"
//--- AUTOGENERATED END ---