#pragma once
#include "Engine/Entities/EntityMacros.hpp"
#include "Engine/Utils/MsgpackHelpers.h"
#include "Engine/Utils/StringUtils.h"
#include "msgpack.hpp"
#include <iostream>
#include <string>

//Can be used to specify a model we want to use. Editor integration so we can easily choose from models
struct ModelSpecifier {
    //The path to get to our zipped models archive on S3 (eg Folder/Mesh~7~)
    CPROPERTY(std::string, FilePath, NO_DEFAULT);
    //The name of the mesh (eg Cube1)
    CPROPERTY(std::string, MeshName, NO_DEFAULT);
    //The name of the file that contains our model
    CPROPERTY(std::string, FileName, NO_DEFAULT);

    bool operator==(const ModelSpecifier& rhs) const {
        if (FilePath != rhs.FilePath) {
            return false;
        }
        if (MeshName != rhs.MeshName) {
            return false;
        }
        return true;
    }

    bool operator!=(const ModelSpecifier& other) const {
        return !(*this == other);
    }

    MSGPACK_PACK_FUNC(FilePath, MeshName, FileName)

    MSGPACK_UNPACK_FUNC(FilePath, MeshName, FileName)
};

//---- AUTOGENERATED ---
#include "Engine/Rendering/ModelSpecifier_autogenerated.h"
//--- AUTOGENERATED END ---