{
 "title": "BabylonBoost Local Server",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(process_resident_memory_bytes, pod)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "Space Fleets Sepcific", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Tick Rate",
   "type": "timeseries",
   "description": "Tick rate per system update",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "current_framerate", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Systems",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "EntitySystem", "legendFormat": "{{SystemName}}" }
   ]
  },
  {
   "title": "PlayerNumber",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "player_number", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Individual Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "ParallelTasks", "legendFormat": "{{SystemName}}" }
   ]
  },
  { "title": "Server General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "MemoryUseage", "legendFormat": "{{MemoryType}}" }
   ]
  },
  {
   "title": "Data Out / Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "DataSendBytes", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "CPU Useage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "CpuUse", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time_running_seconds_total", "legendFormat": "__auto" }
   ]
  }
 ]
}