// function addAutogeneratedHeaderToFile(){
//     //Add the include in the original file if not there
//     // let includeStatement = `\n#include "${relativeDir}/${fileName}_autogenerated.cpp"\n`;
//     // if(code.indexOf(includeStatement) === -1){
//     //     // Find the index of '#pragma once' and add the include statement after it
//     //     let pragmaIndex = code.indexOf('#pragma once');
//     //     if (pragmaIndex !== -1) {
//     //         let insertPosition = code.indexOf('\n', pragmaIndex) + 1;  // position after '#pragma once' line
//     //         code = code.slice(0, insertPosition) + includeStatement + code.slice(insertPosition);
//     //     } else {
//     //         // If there's no '#pragma once', add it at the beginning
//     //         code = includeStatement + code;
//     //     }
//     //     fs.writeFileSync(filePath, code);
//     // }
// }